---
title: 311 Health Department Requests Closure Times for NYC vs Chicago
author: Ginamarie Mastrorilli
date: 4/17/2023
format: 
  html: 
    code-fold: true
---

#### Overview

- Many 311 requests, even though are considered non-emergency, do impact the well being of the requester. 
- 311 requests have the potential to undercover where a city needs to improve on their physical and mental health programs. 
- Requests that are the responsibility of the health department for that city have a significant impact on the mental and physical health of a city. 
    - Longer request completion times can lead to anxiety and increase health issues for residents who have a health related request.
- Inspiration from Scott Minkoff:
    - He states that 311 requests are “The collection of millions of geocoded data points corresponding to problems, and also has the potential to reveal important information about the distribution of physical conditions and government provided goods and services within cities.”
    
    
#### Examples of Health Department Complaint Types:

- Rodents
- Indoor Air Quality
- Restaurant Complaint
- Food Poisoning
- Smoking
- Construction Dust
- Unsanitary Conditions


#### Goal

- Undercover if the method of submission for a 311 request impacts the completion time for that specific request.
    - 311 requests related to health should be completed fairly quickly to ensure livable conditions and do not strain the requester's mental or physical health further.
    - Learning the origin of the request, whether from a phone, submitted online, etc., can help give the city helpful information on which channels need to be followed closer.


#### Data

- Comparison between NYC and Chicago
- NYC
    - Requests are the responsibility of the Department of Health and Mental Hygine
    - Data was collected from NYC OpenData
    - Created Date values from 00:00:00 01/15/2023 and 24:00:00 01/21/2023 
    - Request submission is tracked using the column 'Open Data Channel Type'
        - Online, Phone or Mobile
- Chicago
    - Requests are the responsibility of the Health Department
    - Data was collected from the City of Chicago Data Portal
    - Created date values from 00:00:00 01/15/2023 and 24:00:00 01/21/2023 
    - Request submission is tracked using the column 'Origin' 
    

#### Methods

- Created a column 'duration'
     - Closed Date - Created Date
- Created a binary variable  that represents if the request was over the 80th percentile
    - Allow us to see if the request took a substancial amount of time to complete or not
- Conduct a Kolmogorov–Smirnov(KS) test
    - Goal is to determine if the sets of Online, Mobile and Phone come from the same distribution
    
    
#### Limitations

- ##### Kolmogorov–Smirnov (KS) Test Limitations 

    - Only tests differences in distribution
        - This test will not tell us the nature or direction of the differences 
    - Multiple Comparisons Problem 
        - As the number of datasets being compared increases, the likelihood of finding significant differences between pairs increases
        - Will be using Bonferroni Correction to control for Type I Error
            - $\alpha$ = .05/3 = .0167
            
            
- ##### Data Limitations
    - Only used data from 1 week in January 2023
    - No Data Dictionary for Chicago 311 Requests
        -  Used my own intuition and research to group Chicago Origin column to match NYC Open Data Channel Types
        
            - Online/Other
                - Internet 
                - Chicago Community Safety Coordination Center (CSCC)
                - City Department
                - Alderman Office 
                - Mail
                - Generated in-house 
                - Health Professionals      
                - Open311 Interface

            - Mobile
                - Email 
                - Mobile Device 

            - Phone
                - Phone Call 
    - No clear definition in NYC or Chicago as to what Online, Moblie or Phone are. 
        -  Does not state what type of devices are included in each category.
        - From my own research:
            - Online: requests made through a website
            - Mobile: requests made through email or a mobile app
            - Phone: requests made through calling a phone number
                
                
    
         

### New York City

```{python}
import pandas as pd
nyc311 = pd.read_csv("/Users/ginamastrorilli/Desktop/nyc311_011523-012123_by022023.csv")
nyc = nyc311[nyc311['Agency'] == 'DOHMH']

#create NYC duration column
nyc_dates = nyc[nyc['Closed Date'] >= nyc['Created Date']].dropna(subset=['Closed Date'])
nyc_dates['Created Date'] = pd.to_datetime(nyc_dates['Created Date'])
nyc_dates['Closed Date'] = pd.to_datetime(nyc_dates['Closed Date'])
nyc_dates['duration'] = (nyc_dates['Closed Date'] - nyc_dates['Created Date'])/pd.Timedelta(hours=1)

# to plot NYC duration
import matplotlib.pyplot as plt

plt.hist(nyc_dates['duration'], bins=20, color='green')
plt.xlabel('Duration (hours)')
plt.ylabel('Frequency')
plt.title('Distribution of NYC Request Duration')
plt.show()

#to find 80th percentile 
nyc_80 = nyc_dates['duration'].quantile(0.8)
print(f"The duration value at the 80th percentile for NYC is {nyc_80:.2f} hours")
```

From the graph above we can see that most of the durations fall within 0-100 hours, but the 80th percentile is 47.70 hours. I will create a new variable called 'over46h' to track substantial request completion times for NYC.

```{python}
# creating new binary var that is over 46hr
nyc_dates['over46h'] = (nyc_dates['duration'] > 46).astype(int)

# nyc contigency table
nyc_CT = pd.crosstab(nyc_dates['Open Data Channel Type'], nyc_dates['over46h'])

# to plot
ax = nyc_CT.plot(kind='bar', stacked=False)
ax.set_xlabel('Open Data Channel Type')
ax.set_ylabel('Requests')
ax.set_title('NYC Request Duration by Channel Type')
plt.show()
```

From the graph above, we can see that the distributions and sample sizes are similar but there is an imbalance of data for requests that are completed over 46 hours in NYC.

#### NYC KS Test
- H0: There is no significant difference in the distribution of the three NYC Open Data Channel Types
- Ha: There is a significant difference in the distribution of the three NYC Open Data Channel Types
- $\alpha$ = .0167

```{python}
from itertools import combinations
from scipy.stats import ks_2samp
nyc_open_grouped = nyc_dates.groupby('Open Data Channel Type')['duration']
channel_names = ['ONLINE', 'MOBILE', 'PHONE']
for b1, b2 in combinations(channel_names, 2):
    ks_statistic, p_value = ks_2samp(nyc_open_grouped.get_group(b1), nyc_open_grouped.get_group(b2))
    print(f"{b1} vs {b2}: KS statistic = {ks_statistic:.3f}, p-value = {p_value:.3f}")
    
# to graph
import numpy as np
channel_names = ['ONLINE vs MOBILE', 'ONLINE vs PHONE', 'MOBILE vs PHONE']
ks_stats = [0.111, 0.129, 0.051]
p_values = [0.112, 0.047, 0.931]

# to create plot
fig, ax = plt.subplots(figsize=(8, 6))
x_pos = np.arange(len(channel_names))
bar_colors = ['red', 'green', 'blue']
ax.bar(x_pos, ks_stats, align='center', alpha=0.5, color=bar_colors)
ax.set_xticks(x_pos)
ax.set_xticklabels(channel_names)
ax.set_ylabel('KS statistic')
ax.set_title('New York KS test results')
ax.set_ylim([0, 0.175])

# adding pvalue to the plot
for i, v in enumerate(p_values):
    ax.text(i, ks_stats[i] + 0.01, f"p = {v:.3f}", ha='center')

plt.show()
```

Results: 

- All 3 tests the p-value is greater than  $\alpha$ = .0167
- Fail to reject the null hypothesis and conclude that there is significant evidence to suggest that the distributions of the Open Data Channel Types are different. 


### Chicago

```{python}
chi311 = pd.read_csv("/Users/ginamastrorilli/Desktop/chicago 311_Service_Requests.csv")

chi = chi311[chi311['CREATED_DEPARTMENT'] == 'Health']
#to create Chicago duration column
chi_dates = chi[chi['CLOSED_DATE'] >= chi['CREATED_DATE']].dropna(subset=['CLOSED_DATE'])
chi_dates['CREATED_DATE'] = pd.to_datetime(chi_dates['CREATED_DATE'])
chi_dates['CLOSED_DATE'] = pd.to_datetime(chi_dates['CLOSED_DATE'])
chi_dates['duration'] = (chi_dates['CLOSED_DATE'] - chi_dates['CREATED_DATE'])/pd.Timedelta(hours=1)
chi_dates = chi_dates[chi_dates['duration'] <= 1700]

#to plot Chiacgo duration
plt.hist(chi_dates['duration'], bins=20, color='purple')
plt.xlabel('Duration (hours)')
plt.ylabel('Frequency')
plt.title('Distribution of Chicago Request Duration')
plt.show()

#to calc Chi 80th percentile
chi_80 = chi_dates['duration'].quantile(0.8)
# print the result
print(f"The duration value at the 80th percentile for CHI is {chi_80:.2f} hours")
```

For Chicago, we can see that the distribution is wider compared to NYC. Most of the durations fall between 0-250 hours, but the 80th percentile is 765.70 hours. I will create a new variable called 'over765h' to track substantial request completion times for Chicago.

```{python}
# creating new binary var that is over 765hr
chi_dates['over765h'] = (chi_dates['duration'] > 765).astype(int)

# to regroup Chi origins
categories = {
    'Internet': 'Online/Other',
    'Chicago Community Safety Coordination Center (CSCC)': 'Online/Other',
    'City Department': 'Online/Other',
    'Alderman\'s Office': 'Online/Other',
    'Mail': 'Online/Other',
    'Generated In House': 'Online/Other',
    'HealthProfessionals': 'Online/Other',
    'Open311 Interface': 'Online/Other',
    'E-Mail': 'Mobile',
    'Mobile Device': 'Mobile',
    'Phone Call': 'Phone'
}


chi_dates['Origin_Grouped'] = chi_dates['ORIGIN'].map(categories)

# chi contigency table
chi_CT = pd.crosstab(chi_dates['Origin_Grouped'], chi_dates['over765h'])

#chi graph
ax = chi_CT.plot(kind='bar', stacked=False)
ax.set_xlabel('Origin Type')
ax.set_ylabel('Requests')
ax.set_title('CHI Request Duration by Origin Type')
plt.show()

chi_open_grouped = chi_dates.groupby('Origin_Grouped')['duration']

# to get n for online/other
n_online_other = chi_open_grouped.get_group('Online/Other').shape[0]

# sample Mobile and Phone to match the n
mobile_sample = chi_open_grouped.get_group('Mobile').sample(n=n_online_other, random_state=42)
phone_sample = chi_open_grouped.get_group('Phone').sample(n=n_online_other, random_state=42)
online_other = chi_open_grouped.get_group('Online/Other')
grouped_data = {
    'Online/Other': chi_open_grouped.get_group('Online/Other'),
    'Mobile': mobile_sample,
    'Phone': phone_sample
}

```

From the graph above, we can see that there is a significant difference in sample size between the 3 Origin types in Chicago. To account for this, I sub sampled from the Mobile and Phone groups to match the Online/Other group. 

#### Chicago KS Test
- H0: There is no significant difference in the distribution of the three Chicago Origin Types
- Ha: There is a significant difference in the distribution of the three Chicago Origin Types
- $\alpha$ = .0167

```{python}
origin_names = ['Online/Other', 'Mobile', 'Phone']
chi_open_grouped = chi_dates.groupby('Origin_Grouped')['duration']
# KS test
for b1, b2 in combinations(origin_names, 2):
    ks_statistic, p_value = ks_2samp(grouped_data[b1], grouped_data[b2])
    print(f"{b1} vs {b2}: KS statistic = {ks_statistic:.3f}, p-value = {p_value:.3f}")

# graph 
origin_names = ['Online/Other vs Mobile', 'Online/Other vs Phone', 'Mobile vs Phone']
cks_stats = [0.218, 0.182, 0.109]
cp_values = [0.146, 0.326,  0.903]

# to create plot
fig, ax = plt.subplots(figsize=(8, 6))
x_pos = np.arange(len(origin_names))
bar_colors = ['red', 'green', 'blue']
ax.bar(x_pos, cks_stats, align='center', alpha=0.5, color=bar_colors)
ax.set_xticks(x_pos)
ax.set_xticklabels(origin_names)
ax.set_ylabel('KS statistic')
ax.set_title('Chicago KS test results')
ax.set_ylim([0, 0.3])

# adding pvalue to the plot
for i, v in enumerate(cp_values):
    ax.text(i, cks_stats[i] + 0.01, f"p = {v:.3f}", ha='center')

plt.show()
```

Results: 

- All 3 tests the p-value is greater than  $\alpha$ = .0167
- Fail to reject the null hypothesis and conclude that there is significant evidence to suggest that the distributions of the Origin Types are different. 

### Conclusion

- Overall, both KS Tests from NYC and Chicago concluded there is significant evidence to suggest that the distributions are different. 
- Even though the KS test tells us they do not come from the same distribution, it did not provide any information on the direction or nature of the differences. 

- The NYC Department of Health and Mental Hygine and the Chicago Health Department should look into why there are differences in completion times based off the request origin. 
    - Collect demographic data to see if a certain group of people are more inclined to submit a request through a channel.
    - Create strict definitions on what is included in Online, Mobile and Phone categories. 
        - There could be a technologly limitation which leads to longer processing times.
            - Ex: Online requests may provide more information on the request compared to Phone requests and therefore can be completed quicker. 
    - Make note of where government resources are in the city and test if there is a quicker reponse time if the location of the request is closer to a resource.
    - Test to see if different times of year (Summer vs Winter) have different closure times.
    
- My goal to undercover if the method of submission for a 311 request impacts the completion time for that specific request is not fully complete. 
    - For a future project, I am interested in learning the direction and nature of these differences. 
    - Learning this can give the city helpful information on which channels need to be followed closer and where more resources are necessary to improve the mental and physical health of the city. 

